# Generated by Django 2.0.6 on 2018-06-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_query_date_and_time_of_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
