# Generated by Django 2.0.6 on 2018-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_query_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
