# Generated by Django 2.0.6 on 2018-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_description',
            field=models.TextField(default='Another Stargazer!'),
        ),
    ]
