# Generated by Django 2.0.6 on 2018-06-05 19:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(default='No text'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='No title', max_length=200),
        ),
    ]
