# Generated by Django 2.0.6 on 2018-06-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180605_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Pulsars', 'Pulsars'), ('Quasasrs', 'Quasars')], default='Pulsasrs', max_length=2),
        ),
    ]
