# Generated by Django 2.0.6 on 2018-06-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Pl', 'Pulsars'), ('Qu', 'Quasars')], default='Pl', max_length=2),
        ),
    ]
