# Generated by Django 2.0.6 on 2018-06-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180605_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Pl', 'Pulsars'), ('Qu', 'Quasars')], default='Pl', max_length=255),
        ),
    ]
