# Generated by Django 2.0.6 on 2018-06-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180605_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PR', 'Pulsars'), ('QR', 'Quasars')], default='PR', max_length=255),
        ),
    ]
