# Generated by Django 2.0.6 on 2018-06-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180605_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('PR', 'Pulsars'), ('QR', 'Quasars')], default='PR'),
        ),
    ]
