# Generated by Django 2.0.6 on 2018-06-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('PR', 'Pulsars'), ('QR', 'Quasars')], default='PR'),
        ),
    ]
