# Generated by Django 2.0.6 on 2018-06-05 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_post_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='planetedby',
            field=models.ManyToManyField(related_name='planeted_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
