# Generated by Django 2.0.6 on 2018-06-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comment_planetedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_comments',
            field=models.TextField(default=''),
        ),
    ]
