# Generated by Django 2.0.6 on 2018-06-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20180606_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('STARS&PLANETS', 'Stars and Planets'), ('PULSARS', 'Neutron stars and Pulsars'), ('QUASARS', 'Black holes and Quasars'), ('GALAXIES&COSMOLOGY', 'Galaxies and cosmology'), ('RELATIVITY', 'Relativity in Astro'), ('PARTICLE&QM', 'Particle Physics and Quantum Mechanics in Astro'), ('STRINGTHEORY', 'String Theory in Astro'), ('ASTRONOMY', 'Astronomy'), ('SCIENTIFIC_LITERATURE', 'Scientific Literature')], default='STARS&PLANETS'),
        ),
    ]
