# Generated by Django 2.0.6 on 2018-06-06 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180606_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='starredby',
            field=models.ManyToManyField(blank=True, related_name='starred_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
