# Generated by Django 2.0.6 on 2018-06-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20180606_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('Stars and Planets', 'Stars and Planets'), ('Neutron stars and Pulsars', 'Neutron stars and Pulsars'), ('Black holes and Quasars', 'Black holes and Quasars'), ('Galaxies and Cosmology', 'Galaxies and Cosmology'), ('Relativity in Astro', 'Relativity in Astro'), ('Particle Physics and Quantum Mechanics in Astro', 'Particle Physics and Quantum Mechanics in Astro'), ('String Theory in Astro', 'String Theory in Astro'), ('Astronomy', 'Astronomy'), ('Scientific Literature', 'Scientific Literature')], default='Stars and Planets'),
        ),
    ]
