# Generated by Django 2.0.6 on 2018-06-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20180606_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='planets',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='totalkeeps',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='totalstars',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
