# Generated by Django 2.0.6 on 2018-06-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_keep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keptby',
        ),
    ]
